from coldfront.config.base import INSTALLED_APPS
from coldfront.config.env import ENV


INSTALLED_APPS += [
    'coldfront.plugins.customizable_forms',
]

CUSTOMIZABLE_FORMS_ALLOCATION_VIEWS = ENV.list('CUSTOMIZABLE_FORMS_ALLOCATION_VIEWS', default={})
CUSTOMIZABLE_FORMS_GENERIC_ALLOCATION_VIEW = ENV.str('CUSTOMIZABLE_FORMS_GENERIC_ALLOCATION_VIEW', default='')
CUSTOMIZABLE_FORMS_ADDITIONAL_PERSISTENCE_FUNCTIONS = ENV.list('CUSTOMIZABLE_FORMS_ADDITIONAL_PERSISTENCE_FUNCTIONS', default={})
