from coldfront.config.base import INSTALLED_APPS
from coldfront.config.env import ENV

INSTALLED_APPS += [
    "coldfront.plugins.ldap_misc",
]


LDAP_ENABLE_PROJECT_PI_ELIGIBLE_ADS_GROUPS = ENV.bool("LDAP_ENABLE_PROJECT_PI_ELIGIBLE_ADS_GROUPS", default=True)
LDAP_PROJECT_PI_ELIGIBLE_ADS_GROUPS = ENV.list("LDAP_PROJECT_PI_ELIGIBLE_ADS_GROUPS", default=[])
LDAP_RESOURCE_ENABLE_ACCOUNT_CHECKING = ENV.bool("LDAP_RESOURCE_ENABLE_ACCOUNT_CHECKING", default=True)
LDAP_RESOURCE_ACCOUNTS = ENV.dict("LDAP_RESOURCE_ACCOUNTS", default={})
LDAP_ENABLE_USER_INFO = ENV.bool("LDAP_ENABLE_USER_INFO", default=True)
