# Generated by Django 5.2.17 on 2026-08-28 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_change_request', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpichangerequestresourceapproval',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_approvals', to='pi_change_request.projectpichangerequest'),
        ),
        migrations.AlterField(
            model_name='projectpichangerequestresourceapprovalstatuschoice',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='projectpichangerequeststatuschoice',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='projectpichangerequestuserapproval',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_approvals', to='pi_change_request.projectpichangerequest'),
        ),
        migrations.AlterField(
            model_name='projectpichangerequestuserapprovalstatuschoice',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddConstraint(
            model_name='projectpichangerequestuserapproval',
            constraint=models.UniqueConstraint(fields=('request', 'user'), name='unique_user_approval_per_request'),
        ),
    ]
