# Generated by Django 5.2.16 on 2026-08-06 16:52

from django.db import migrations


def seed_pi_change_request_statuses(apps, schema_editor):
    StatusChoice = apps.get_model("pi_change_request", "ProjectPiChangeRequestStatusChoice")
    ApprovalStatusChoice = apps.get_model("pi_change_request", "ProjectPiChangeRequestApprovalStatusChoice")

    request_statuses = ["Complete", "Awaiting Approvals", "Blocked", "Ready", "New", "Rejected"]
    for name in request_statuses:
        StatusChoice.objects.get_or_create(name=name)

    approval_statuses = ["Approved", "Pending", "Denied"]
    for name in approval_statuses:
        ApprovalStatusChoice.objects.get_or_create(name=name)


class Migration(migrations.Migration):
    dependencies = [
        ("pi_change_request", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_pi_change_request_statuses),
    ]
