# Generated by Django 5.2.17 on 2026-09-22 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_change_request', '0004_seed_cancelled_approval_status'),
        ('resource', '0003_auto_20210817_1130_squashed_0008_alter_historicalresource_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='projectpichangerequestresourceapproval',
            constraint=models.UniqueConstraint(fields=('request', 'resource'), name='unique_resource_approval_per_request'),
        ),
    ]
