# Generated by Django 5.2.17 on 2026-09-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_change_request', '0005_projectpichangerequestresourceapproval_unique_resource_approval_per_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprojectpichangerequestresourceapproval',
            name='reason',
            field=models.TextField(blank=True, default='', help_text='Reason given when the approval was denied.'),
        ),
        migrations.AddField(
            model_name='historicalprojectpichangerequestuserapproval',
            name='reason',
            field=models.TextField(blank=True, default='', help_text='Reason given when the approval was declined.'),
        ),
        migrations.AddField(
            model_name='projectpichangerequestresourceapproval',
            name='reason',
            field=models.TextField(blank=True, default='', help_text='Reason given when the approval was denied.'),
        ),
        migrations.AddField(
            model_name='projectpichangerequestuserapproval',
            name='reason',
            field=models.TextField(blank=True, default='', help_text='Reason given when the approval was declined.'),
        ),
    ]
