# Generated by Django 4.2.11 on 2025-10-16 18:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models


class Migration(migrations.Migration):

    replaces = [
        ("project", "0002_auto_20220721_1202"),
        ("project", "0003_auto_20220829_0940"),
        ("project", "0004_projectadminaction"),
        ("project", "0005_auto_20221111_0837"),
        ("project", "0006_auto_20230615_1125"),
        ("project", "0007_alter_projectadminaction_action"),
        ("project", "0008_attributetype_projectattribute_and_more"),
        ("project", "0009_alter_project_description_alter_project_title"),
        ("project", "0010_alter_projectadminaction_action"),
        ("project", "0011_alter_project_options_and_more"),
    ]

    dependencies = [
        ("project", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTypeChoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["title"],
                "permissions": (
                    ("can_view_all_projects", "Can view all projects"),
                    (
                        "can_review_pending_projects",
                        "Can review pending project requests/reviews",
                    ),
                ),
            },
        ),
        migrations.RenameField(
            model_name="historicalprojectreview",
            old_name="reason_for_not_updating_project",
            new_name="project_updates",
        ),
        migrations.RenameField(
            model_name="projectreview",
            old_name="reason_for_not_updating_project",
            new_name="project_updates",
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="max_managers",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="private",
            field=models.BooleanField(
                default=False,
                help_text="A private project will not show up in the PI search results if someone searchs for you/your PI.",
            ),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="requestor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalprojectreview",
            name="allocation_renewals",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="max_managers",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="private",
            field=models.BooleanField(
                default=False,
                help_text="A private project will not show up in the PI search results if someone searchs for you/your PI.",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="requestor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requestor_user",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectreview",
            name="allocation_renewals",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectusermessage",
            name="is_private",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="description",
            field=models.TextField(
                default="",
                help_text="\nPlease provide a brief description or abstract about your project including any applications or\nworkflows you intend to use, and how you primarily intend to use the system, including if PHI will\nbe stored. Please include your area of research and your department. If this is for a class please\nput the approximate class size.\n",
                validators=[
                    django.core.validators.MinLengthValidator(
                        10, "The project description must be > 10 characters."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="slurm_account_name",
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="This cannot be changed once your project is submitted. Class projects expire at the end of every semester. Research projects expire once a year.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="project.projecttypechoice",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                default="",
                help_text="\nPlease provide a brief description or abstract about your project including any applications or\nworkflows you intend to use, and how you primarily intend to use the system, including if PHI will\nbe stored. Please include your area of research and your department. If this is for a class please\nput the approximate class size.\n",
                validators=[
                    django.core.validators.MinLengthValidator(
                        10, "The project description must be > 10 characters."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="pi_username",
            field=models.CharField(
                blank=True,
                help_text="\nRequired if you will not be the PI of this project. Only faculty and staff can be the PI. They are\nrequired to log onto the site at least once before they can be added.\n",
                max_length=20,
                verbose_name="PI Username",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="slurm_account_name",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="project",
            name="type",
            field=models.ForeignKey(
                help_text="This cannot be changed once your project is submitted. Class projects expire at the end of every semester. Research projects expire once a year.",
                on_delete=django.db.models.deletion.CASCADE,
                to="project.projecttypechoice",
            ),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="pi_username",
            field=models.CharField(
                blank=True,
                help_text="\nRequired if you will not be the PI of this project. Only faculty and staff can be the PI. They are\nrequired to log onto the site at least once before they can be added.\n",
                max_length=20,
                verbose_name="PI Username",
            ),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="class_number",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="class_number",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.CreateModel(
            name="ProjectDescriptionRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AttributeType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectAttribute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("value", models.CharField(max_length=128)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="historicalproject",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical project",
                "verbose_name_plural": "historical projects",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalprojectreview",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical project review",
                "verbose_name_plural": "historical project reviews",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalprojectuser",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical project user",
                "verbose_name_plural": "historical Project User Status",
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["title"],
                "permissions": (
                    ("can_view_all_projects", "Can view all projects"),
                    (
                        "can_review_pending_project_reviews",
                        "Can review pending project reviews",
                    ),
                ),
            },
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalprojectreview",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalprojectuser",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="projectstatuschoice",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="projectuserrolechoice",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="projectuserstatuschoice",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name="ProjectAttributeUsage",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "project_attribute",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="project.projectattribute",
                    ),
                ),
                ("value", models.FloatField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectAttributeType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("has_usage", models.BooleanField(default=False)),
                ("is_required", models.BooleanField(default=False)),
                ("is_unique", models.BooleanField(default=False)),
                ("is_private", models.BooleanField(default=True)),
                ("is_changeable", models.BooleanField(default=False)),
                (
                    "attribute_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.attributetype",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="projectattribute",
            name="proj_attr_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.projectattributetype",
            ),
        ),
        migrations.AddField(
            model_name="projectattribute",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="project.project"
            ),
        ),
        migrations.CreateModel(
            name="HistoricalProjectAttributeUsage",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("value", models.FloatField(default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project_attribute",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="project.projectattribute",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical project attribute usage",
                "verbose_name_plural": "historical project attribute usages",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProjectAttributeType",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("has_usage", models.BooleanField(default=False)),
                ("is_required", models.BooleanField(default=False)),
                ("is_unique", models.BooleanField(default=False)),
                ("is_private", models.BooleanField(default=True)),
                ("is_changeable", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "attribute_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="project.attributetype",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical project attribute type",
                "verbose_name_plural": "historical project attribute types",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProjectAttribute",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("value", models.CharField(max_length=128)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proj_attr_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="project.projectattributetype",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical project attribute",
                "verbose_name_plural": "historical project attributes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                db_collation="utf8mb4_0900_ai_ci",
                default="",
                help_text="\nPlease provide a brief description or abstract about your project including any applications or\nworkflows you intend to use, and how you primarily intend to use the system, including if PHI will\nbe stored. Please include your area of research and your department. If this is for a class please\nput the approximate class size.\n",
                validators=[
                    django.core.validators.MinLengthValidator(
                        10, "The project description must be > 10 characters."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(db_collation="utf8mb4_0900_ai_ci", max_length=255),
        ),
        migrations.CreateModel(
            name="ProjectAdminAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("action", models.CharField(max_length=256)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["title"],
                "permissions": (
                    ("can_view_all_projects", "Can view all projects"),
                    (
                        "can_review_pending_projects",
                        "Can review pending project requests/reviews",
                    ),
                ),
            },
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="max_managers",
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="project",
            name="max_managers",
            field=models.IntegerField(default=3),
        ),
    ]
