# Generated by Django 4.2.23 on 2025-10-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_historicalproject_institution_project_institution"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalproject",
            name="class_number",
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="pi_username",
        ),
        migrations.RemoveField(
            model_name="project",
            name="class_number",
        ),
        migrations.RemoveField(
            model_name="project",
            name="pi_username",
        ),
    ]
