# Generated by Django 5.2.14 on 2026-08-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_project_description_alter_project_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='slurm_account_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slurm_account_name',
        ),
    ]
