# Generated by Django 5.2.14 on 2026-07-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_userprofile_max_class_projects_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='limit_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
