# Generated by Django 4.2.23 on 2026-07-22 20:03

import coldfront.plugins.advanced_search.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsavedsearch',
            name='query_data',
            field=models.JSONField(default=dict, help_text='JSON representation of the search query parameters', validators=[coldfront.plugins.advanced_search.validators.validate_query_data]),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='query_data',
            field=models.JSONField(default=dict, help_text='JSON representation of the search query parameters', validators=[coldfront.plugins.advanced_search.validators.validate_query_data]),
        ),
    ]
