# Generated by Django 4.2.11 on 2025-06-26 14:31

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resource", "0003_auto_20210817_1130_squashed_0008_alter_historicalresource_options_and_more"),
        ("allocation", "0003_auto_20191018_1049"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocation",
            name="access_level",
            field=models.CharField(
                blank=True,
                choices=[("Masked", "Masked"), ("Unmasked", "Unmasked")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="allocation",
            name="account_number",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="applications_list",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="confirm_understanding",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="data_management_plan",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="department_full_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="department_short_name",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="devices_ip_addresses",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="dl_workflow",
            field=models.CharField(
                blank=True,
                choices=[("No", "No"), ("Yes", "Yes")],
                max_length=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="allocation",
            name="fiscal_officer",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="for_coursework",
            field=models.CharField(
                blank=True,
                choices=[("No", "No"), ("Yes", "Yes")],
                max_length=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="allocation",
            name="grand_challenge_program",
            field=models.CharField(
                blank=True,
                choices=[
                    ("healthinitiative", "Precision Health Initiative"),
                    ("envchange", "Prepared for Environmental Change"),
                    ("addiction", "Responding to the Addiction Crisis"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="allocation",
            name="is_grand_challenge",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="it_pros",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="leverage_multiple_gpus",
            field=models.CharField(
                blank=True,
                choices=[("No", "No"), ("Yes", "Yes")],
                max_length=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="allocation",
            name="phi_association",
            field=models.CharField(
                blank=True,
                choices=[("No", "No"), ("Yes", "Yes")],
                max_length=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="allocation",
            name="primary_contact",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="secondary_contact",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="sub_account_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="system",
            field=models.CharField(
                blank=True,
                choices=[("Carbonate", "Carbonate"), ("BigRed3", "Big Red 3")],
                max_length=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="allocation",
            name="training_or_inference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Training", "Training"),
                    ("Inference", "Inference"),
                    ("Both", "Both"),
                ],
                max_length=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="allocation",
            name="use_indefinitely",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="allocation",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalallocation",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AllocationChangeStatusChoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AllocationUserRequestStatusChoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="allocation",
            name="campus_affiliation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BL", "IU Bloomington"),
                    ("IN", "IUPUI (Indianapolis)"),
                    ("CO", "IUPUC (Columbus)"),
                    ("EA", "IU East (Richmond)"),
                    ("FW", "IU Fort Wayne"),
                    ("CO", "IU Kokomo"),
                    ("NW", "IU Northwest (Gary)"),
                    ("SB", "IU South Bend"),
                    ("SE", "IU Southeast (New Albany)"),
                    ("OR", "Other"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="allocation",
            name="data_manager",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="email",
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="faculty_email",
            field=models.EmailField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="first_name",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="is_changeable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="allocation",
            name="last_name",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="project_directory_name",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="storage_space_unit",
            field=models.CharField(
                blank=True,
                choices=[("GB", "GB"), ("TB", "TB")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="allocation",
            name="store_ephi",
            field=models.CharField(
                blank=True,
                choices=[("No", "No"), ("Yes", "Yes")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="allocation",
            name="total_cost",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="url",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="allocationattributetype",
            name="is_changeable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalallocation",
            name="is_changeable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalallocationattributetype",
            name="is_changeable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="allocation",
            name="storage_space",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AllocationUserRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "allocation_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="allocation.allocationuser",
                    ),
                ),
                (
                    "allocation_user_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="allocation.allocationuserstatuschoice",
                    ),
                ),
                (
                    "requestor_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="allocation.allocationuserrequeststatuschoice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AllocationInvoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("account_number", models.CharField(max_length=9)),
                (
                    "sub_account_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="allocation.allocation",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="allocation.allocationstatuschoice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AllocationChangeRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("end_date_extension", models.IntegerField(blank=True, null=True)),
                ("justification", models.TextField()),
                ("notes", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="allocation.allocation",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="allocation.allocationchangestatuschoice",
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="allocation",
            name="admin_ads_group",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="data_management_responsibilities",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="group_account_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="group_account_name_exists",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="phone_number",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="terms_of_service",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="user_ads_group",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="confirm_best_practices",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="actively_billing",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="billable_amount_annual",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="billable_amount_monthly",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="billing_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="billing_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="billing_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="fileset",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="gpu_workflow",
            field=models.CharField(
                blank=True,
                choices=[("No", "No"), ("Yes", "Yes")],
                max_length=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="allocation",
            name="mou_link",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="organization",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="quota_files",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="share_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="allocation",
            name="share_path",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelOptions(
            name="allocation",
            options={
                "ordering": ["end_date"],
                "permissions": (
                    ("can_view_all_allocations", "Can view all allocations"),
                    (
                        "can_review_allocation_requests",
                        "Can review allocation requests",
                    ),
                    ("can_manage_invoice", "Can manage invoice"),
                    ("can_remove_allocation", "Can remove allocation"),
                ),
            },
        ),
        migrations.AddField(
            model_name="allocationattributetype",
            name="linked_resources",
            field=models.ManyToManyField(blank=True, to="resource.resource"),
        ),
        migrations.AddField(
            model_name="allocationattributetype",
            name="linked_resource_attribute_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="resource.resourceattributetype",
            ),
        ),
        migrations.AddField(
            model_name="historicalallocationattributetype",
            name="linked_resource_attribute_type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="resource.resourceattributetype",
            ),
        ),
        migrations.CreateModel(
            name="AllocationUserRoleChoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("is_user_default", models.BooleanField(default=False)),
                ("is_manager_default", models.BooleanField(default=False)),
                (
                    "resources",
                    models.ManyToManyField(blank=True, to="resource.resource"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="allocationuser",
            name="role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="allocation.allocationuserrolechoice",
            ),
        ),
        migrations.AddField(
            model_name="historicalallocationuser",
            name="role",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="allocation.allocationuserrolechoice",
            ),
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="access_level",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="account_number",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="actively_billing",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="admin_ads_group",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="applications_list",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="billable_amount_annual",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="billable_amount_monthly",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="billing_end_date",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="billing_rate",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="billing_start_date",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="campus_affiliation",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="confirm_best_practices",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="confirm_understanding",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="data_management_plan",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="data_management_responsibilities",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="data_manager",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="department_full_name",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="department_short_name",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="devices_ip_addresses",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="dl_workflow",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="email",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="faculty_email",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="fileset",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="fiscal_officer",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="for_coursework",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="gpu_workflow",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="grand_challenge_program",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="group_account_name",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="group_account_name_exists",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="is_grand_challenge",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="it_pros",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="leverage_multiple_gpus",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="mou_link",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="phi_association",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="primary_contact",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="project_directory_name",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="quota_files",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="secondary_contact",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="share_name",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="share_path",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="storage_space",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="storage_space_unit",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="store_ephi",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="sub_account_number",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="system",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="terms_of_service",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="total_cost",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="training_or_inference",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="url",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="use_indefinitely",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="user_ads_group",
        ),
        migrations.AlterModelOptions(
            name="historicalallocation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical allocation",
                "verbose_name_plural": "historical allocations",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalallocationattribute",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical allocation attribute",
                "verbose_name_plural": "historical allocation attributes",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalallocationattributetype",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical allocation attribute type",
                "verbose_name_plural": "historical allocation attribute types",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalallocationattributeusage",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical allocation attribute usage",
                "verbose_name_plural": "historical allocation attribute usages",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalallocationuser",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical allocation user",
                "verbose_name_plural": "historical Allocation User Status",
            },
        ),
        migrations.AlterField(
            model_name="historicalallocation",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalallocationattribute",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalallocationattributetype",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalallocationattributeusage",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.CreateModel(
            name="HistoricalAllocationChangeRequest",
            fields=[
                (
                    "id",
                    models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("end_date_extension", models.IntegerField(blank=True, null=True)),
                ("justification", models.TextField()),
                ("notes", models.CharField(blank=True, max_length=512, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "allocation",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="allocation.allocation",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="allocation.allocationchangestatuschoice",
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical allocation change request",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
                "verbose_name_plural": "historical allocation change requests",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterField(
            model_name="historicalallocationuser",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.CreateModel(
            name="HistoricalAllocationUserRequest",
            fields=[
                (
                    "id",
                    models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "allocation_user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="allocation.allocationuser",
                    ),
                ),
                (
                    "allocation_user_status",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="allocation.allocationuserstatuschoice",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requestor_user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="allocation.allocationuserrequeststatuschoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical allocation user request",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
                "verbose_name_plural": "historical allocation user requests",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="AllocationAttributeChangeRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("new_value", models.CharField(max_length=128)),
                (
                    "allocation_attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="allocation.allocationattribute",
                    ),
                ),
                (
                    "allocation_change_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="allocation.allocationchangerequest",
                    ),
                ),
                ("old_value", models.CharField(default=0, max_length=128)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalAllocationAttributeChangeRequest",
            fields=[
                (
                    "id",
                    models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("new_value", models.CharField(max_length=128)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "allocation_attribute",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="allocation.allocationattribute",
                    ),
                ),
                (
                    "allocation_change_request",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="allocation.allocationchangerequest",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("old_value", models.CharField(default=0, max_length=128)),
            ],
            options={
                "verbose_name": "historical allocation attribute change request",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
                "verbose_name_plural": "historical allocation attribute change requests",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterField(
            model_name="allocationattribute",
            name="value",
            field=models.CharField(db_collation="utf8mb4_0900_ai_ci", max_length=128),
        ),
        migrations.CreateModel(
            name="AllocationAdminAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("action", models.CharField(max_length=256)),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="allocation.allocation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="allocation",
            options={
                "ordering": ["end_date"],
                "permissions": (
                    ("can_view_all_allocations", "Can view all allocations"),
                    (
                        "can_review_allocation_requests",
                        "Can review allocation requests",
                    ),
                    ("can_manage_invoice", "Can manage invoice"),
                ),
            },
        ),
    ]
