# Generated by Django 4.2.11 on 2025-06-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "allocation",
            "0004_auto_20211005_1108_squashed_0018_alter_allocation_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="allocationattributechangerequest",
            name="old_value",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="historicalallocationattributechangerequest",
            name="old_value",
            field=models.CharField(max_length=128),
        ),
    ]
