# Generated by Django 4.2.23 on 2025-11-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "allocation",
            "0019_alter_allocationattributechangerequest_old_value_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="allocationattribute",
            name="value",
            field=models.CharField(db_collation="utf8mb4_unicode_ci", max_length=128),
        ),
    ]
