# Generated by Django 4.2.11 on 2025-10-13 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceTypeChoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalMaintenance",
            fields=[
                (
                    "id",
                    models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name="ID"),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("title", models.CharField(max_length=512)),
                (
                    "prior_message",
                    models.CharField(max_length=512, verbose_name="upcoming maintenance message"),
                ),
                (
                    "during_message",
                    models.CharField(max_length=512, verbose_name="during maintenance message"),
                ),
                (
                    "start_date_time",
                    models.DateTimeField(verbose_name="maintenance start time"),
                ),
                (
                    "end_date_time",
                    models.DateTimeField(verbose_name="maintenance end time"),
                ),
                (
                    "notification_days",
                    models.IntegerField(verbose_name="days to notify users before maintenance"),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="maintenance_mode.maintenancetypechoice",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical maintenance",
                "verbose_name_plural": "historical maintenances",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Maintenance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("title", models.CharField(max_length=512)),
                (
                    "prior_message",
                    models.CharField(max_length=512, verbose_name="upcoming maintenance message"),
                ),
                (
                    "during_message",
                    models.CharField(max_length=512, verbose_name="during maintenance message"),
                ),
                (
                    "start_date_time",
                    models.DateTimeField(verbose_name="maintenance start time"),
                ),
                (
                    "end_date_time",
                    models.DateTimeField(verbose_name="maintenance end time"),
                ),
                (
                    "notification_days",
                    models.IntegerField(verbose_name="days to notify users before maintenance"),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintenance_mode.maintenancetypechoice",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date_time"],
            },
        ),
    ]
