# Generated by Django 4.2.23 on 2025-11-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance_mode", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalmaintenance",
            old_name="during_message",
            new_name="maintenance_message",
        ),
        migrations.RenameField(
            model_name="historicalmaintenance",
            old_name="prior_message",
            new_name="upcoming_message",
        ),
        migrations.RenameField(
            model_name="maintenance",
            old_name="during_message",
            new_name="maintenance_message",
        ),
        migrations.RenameField(
            model_name="maintenance",
            old_name="prior_message",
            new_name="upcoming_message",
        ),
        migrations.AddField(
            model_name="historicalmaintenance",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="maintenance",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
