# Generated by Django 4.2.11 on 2025-10-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource", "0002_auto_20191017_1141"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalresourceattribute",
            name="value",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="resourceattribute",
            name="value",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="review_groups",
            field=models.ManyToManyField(blank=True, related_name="review_groups_resource_set", to="auth.group"),
        ),
        migrations.AddField(
            model_name="historicalresourceattributetype",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resourceattributetype",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalresourceattribute",
            name="check_if_username_exists",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalresourceattribute",
            name="is_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalresourceattribute",
            name="resource_account_is_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resourceattribute",
            name="check_if_username_exists",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resourceattribute",
            name="is_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resourceattribute",
            name="resource_account_is_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalresource",
            name="requires_user_roles",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resource",
            name="requires_user_roles",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelOptions(
            name="historicalresource",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical resource",
                "verbose_name_plural": "historical resources",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalresourceattribute",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical resource attribute",
                "verbose_name_plural": "historical resource attributes",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalresourceattributetype",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical resource attribute type",
                "verbose_name_plural": "historical resource attribute types",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalresourcetype",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical resource type",
                "verbose_name_plural": "historical resource types",
            },
        ),
        migrations.AlterField(
            model_name="historicalresource",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalresourceattribute",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalresourceattributetype",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalresourcetype",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="resource",
            name="linked_resources",
            field=models.ManyToManyField(blank=True, to="resource.resource"),
        ),
    ]
